version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
  web:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./run.sh
